### ISSUE TITLE
Feature request: auto-merge

### ISSUE THREAD

**Issue by huehnerlady** [gradle-update/update-gradle-wrapper-action#120]
I would see this as a low priority thing, but as we try that [beta feature of github](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request) more and more I thought it might be a nice thing be able to enable that in the pull request created by this action.

Very vague idea in my head, but if you are interested in that idea I am happy to spend a bit more time in developing the idea a bit firther :)

**Comment by cristiangreco** [comment]
Hey @huehnerlady what work needs to be done in order to support auto-merge for pull requests create by the action? I thought it was just a repository setting that applies to all PR of a certain type?

**Comment by huehnerlady** [comment]
@cristiangreco I do not know if you can add a flag for it when you create the PR via API yet.
It is not automatically enabled. You basically enable the feature in the settings of every repo, and then once you created a pull request you then have a button in every pull request to enable auto-merge.

So you have to enable it per repository and then per Pull Request. So I assume either a flag in the API already exists, or it will be added soon.

**Comment by cristiangreco** [comment]
@huehnerlady AFAICS there's no way in the [PR creation](https://docs.github.com/en/rest/reference/pulls#create-a-pull-request) API to specify that it can be auto-merged. It seems that, once enabled, auto-merge applies automatically to all PRs that would normally require a review or a check to pass: https://github.blog/changelog/2020-12-16-pull-request-auto-merge-public-beta/

Did you have a chance to test auto-merge in one of your repositories?

**Comment by huehnerlady** [comment]
I have it enabled in the repository I test your action with and as shown in the screenshot above this is a manual process to enable per pull request (which I like)

I guess as this is still in beta maybe they did not update the API yet?

**Comment by huehnerlady** [comment]
Not sure if this helps, but the GraphQL API for pull requests now supports the auto-merge function. See [here[(https://docs.github.com/en/graphql/reference/objects#automergerequest)

Also the auto-merge function is now out of beta, see [here](https://github.blog/changelog/2021-02-04-pull-request-auto-merge-is-now-generally-available/)

**Comment by huehnerlady** [comment]
@cristiangreco the auto-merge feature seems to be out of beta for a while now. Any plan to implement the possibility here? had about 50 PRs this morning for the new release and with the auto-merge feature it would actually have saved me 50 clicks today 😉

**Comment by huehnerlady** [comment]
@cristiangreco is there an update on this? :) Would be really really handy feature 🙂

**Comment by cristiangreco** [comment]
Hi @huehnerlady! 👋 

Unfortunately the `auto_merge` feature is currently only available through the GraphQL API. As we use the Rest API in this project instead we can't enable it yet.

**Comment by huehnerlady** [comment]
oh I see, that is a shame. Why can you not use the GraphQL API?Is that a problem as such?

**Comment by cristiangreco** [comment]
> oh I see, that is a shame. Why can you not use the GraphQL API?Is that a problem as such?

No, it should be possible to switch from Rest to GraphQL API easily I guess, but haven't looked into it.

**Comment by bbednarek** [comment]
Any updates on this? Do you have any plans supporting auto merge in the future?

**Comment by cristiangreco** [comment]
Hi @bbednarek, will try to look into this asap (I'm working on another feature request at the moment).

**Comment by bbednarek** [comment]
@cristiangreco it has been a while. Do you plan to support auto-merge?

**Comment by kkocel** [comment]
@bbednarek mybe you can enable auto-merge like that?

```yml
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

**Comment by huehnerlady** [comment]
@kkocel of course there are always possibilities to hack something together so it will somehow work. My hope is that it will be supported natively at some point so hopefully you do not have to use so many hacks anymore :)

**Comment by kkocel** [comment]
@huehnerlady code snippet I've sent is a part of the official GitHub documentation ( https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request ). TBH GitHub Actions are one huge hack and some things work here by miracle/accident, so ¯\_(ツ)_/¯

**Comment by bbednarek** [comment]
@kkocel Thanks for the work-around. I tried it out and I managed to make it work.

The challenge was that I run update gradle wrapper action workflow as a cron and then I use personal access token of a dedicated account which creates PR (info [here](https://github.com/gradle-update/update-gradle-wrapper-action#running-ci-workflows-in-pull-requests-created-by-the-action)), because I want to trigger action workflows.

Then once PR is created I had to extend the same workflow file with additional step to enable auto-merge in PR only. I decided to use labels for that purpose. 

Please note that we use self hosted runners, thus I had to extend our Dockerfile and install [gh cli](https://github.com/cli/cli/blob/trunk/docs/install_linux.md). You can skip this step if you use github hosted runners.
```
FROM summerwind/actions-runner:latest

RUN type -p curl >/dev/null || sudo apt install curl -y

RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
    && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && sudo apt update \
    && sudo apt install gh -y \
    && sudo apt-get install openjdk-11-jdk -y \
    && sudo rm -rf /var/lib/apt/lists/*
```

Maybe someone will find it helpful, so this is my current workflow file. 
```
name: Update Gradle Wrapper

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    types: [ labeled, opened, synchronize, reopened ]
    paths:
      - '.github/workflows/update-gradle-wrapper.yml'
      - 'gradle/**'
      - 'gradlew'
  schedule:
    - cron: "0 9 * * SUN"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-gradle-wrapper:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          labels: dependencies
          repo-token: ${{ secrets.GH_WORKFLOW_TOKEN }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Enable auto-merge
        if: contains(github.event.pull_request.labels.*.name, 'dependencies')
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
