### ISSUE TITLE
Reviewers not being assigned 

### ISSUE THREAD

**Issue by WhosNickDoglio** [gradle-update/update-gradle-wrapper-action#39]
[This is my workflow file](https://github.com/WhosNickDoglio/Yahoo-Fantasy-Client/blob/trunk/.github/workflows/update_gradle.yml)

```
name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          repo-token: ${{ secrets.GRADLE_UPGRADE_TOKEN }}
          reviewers: WhosNickDoglio
          labels: housekeeping
```

and [this is the PR](https://github.com/WhosNickDoglio/Yahoo-Fantasy-Client/pull/15) it opened last night, the workflow file has it setting myself as the reviewer but I wasn't assigned on the PR. 

Let me know if I set it up wrong or if there's anything else I can provide 👍

**Comment by cristiangreco** [comment]
@WhosNickDoglio thanks for reporting this. 

So what happened is that you couldn't be assigned as a reviewer because you're using your own PAT in the workflow (in fact, you appear as the author of the PR).

Looking at the [workflow logs](https://github.com/WhosNickDoglio/Yahoo-Fantasy-Client/actions/runs/309703749) you'll find the error.

```
Unable to set all the PR reviewers, got error: Review cannot be requested from pull request author.
```

This is unfortunately a limitation of the GitHub API.

Not sure what is the best workaround here. Maybe the action could tag you in a PR comment so that you receive a notification?

**Comment by WhosNickDoglio** [comment]
This is what I get for opening an issue first thing in the morning without doing any debugging 🙃

All of that makes complete sense! 

Yeah tagging me in a comment would work, anything that would send me a notification would be fine with me 👍 

Excellent action btw 🎉

**Comment by huehnerlady** [comment]
Hi, I have the same problem, just slightly different. I would like to set a team as reviewers. There I get the warning:

```
Warning: Unable to set all the PR reviewers, check usernames are correct.
```

my line of code:
```
jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: dependencies
          reviewers: my-orga/my-team
      - uses: gradle/wrapper-validation-action@v1
```

Any idea how to achieve that?
