### ISSUE TITLE
Teams as reviewers are not assigned

### ISSUE THREAD

**Issue by huehnerlady** [gradle-update/update-gradle-wrapper-action#60]
Hi, I have a similar issue to #39, but here I talk about a team of an organization as a reviewer.

There I get the warning:

`Warning: Unable to set all the PR reviewers, check usernames are correct.`

my github action file:

```
name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    # "weekly" https://crontab.guru/every-week
    - cron: "0 0 * * 0"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: my-orga/my-team
      - uses: gradle/wrapper-validation-action@v1
```

Any idea how to achieve that?
