### ISSUE TITLE
update gradle wrapper action is failing

### ISSUE THREAD

**Issue by huehnerlady** [gradle-update/update-gradle-wrapper-action#645]
Hi,

currently we have the problem, that the gradle wrapper action fails, if the update contains breaking changes (eg. from 7.6 to 8 in [this repository](https://github.com/europace/docker-publish-gradle-plugin/actions))

We do not have necessarily monitoring set around that so it is not easily spotted.

Is there a possibility to add functionality for that? eg. that an issue is created to reflect the problem, or a PR is still created with the change in wrapper, but is would not build, so the team can check what is going on?

**Comment by koppor** [comment]
Isn't this about the unix tool philosophy?

You can run [`gh issue create`](https://cli.github.com/manual/gh_issue_create).

```yaml
    - name: Create Issue on Failure
      if: failure()
      run: |
        ISSUE_EXISTS=$(gh issue list --search "Gradle update failed --state open --limit 1 | wc -l)
        if [ "$ISSUE_EXISTS" -eq "0" ]; then
          gh issue create --title "Gradle update failure" --body "Gradle update failed"
        fi
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
```
