### ISSUE TITLE
action fails to update from rc to stable version when on `release-candidate` channel

### ISSUE THREAD

**Issue by JKatzwinkel** [gradle-update/update-gradle-wrapper-action#925]
Hi, thanks for the great work!

Updates from version `8.14-rc-x` to `8.14` fail with the error message `❌ Invalid URL` when the action is configured to track `release-candidate` as its `release-channel`:

```yaml

  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4.2.2

      - name: update gradle wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2.1.0
        with:
          release-channel: release-candidate
```

![Image](https://github.com/user-attachments/assets/226bb729-ac16-42cd-a355-030e07ce682c)
https://github.com/JKatzwinkel/gradlew-update-action-issue-demo/actions/runs/14751948144/job/41411265569

---

Here's a demo reproducing the issue: https://github.com/JKatzwinkel/gradlew-update-action-issue-demo

This only happens on the rc release channel. After changing the channel to `stable`, everything works fine.
